import { partone as d1p1, parttwo as d1p2} from './01/code';
import { partone as d2p1, parttwo as d2p2} from './02/code';
import { partone as d3p1, parttwo as d3p2} from './03/code';
import { partone as d4p1, parttwo as d4p2} from './04/code';
import { partone as d5p1, parttwo as d5p2} from './05/code';
import { partone as d6p1, parttwo as d6p2} from './06/code';
import { partone as d7p1, parttwo as d7p2} from './07/code';
import { partone as d8p1, parttwo as d8p2} from './08/code';
import { partone as d9p1, parttwo as d9p2} from './09/code';
import { partone as d10p1, parttwo as d10p2} from './10/code';
import { partone as d11p1, parttwo as d11p2} from './11/code';
import { partone as d12p1, parttwo as d12p2} from './12/code';
import { partone as d13p1, parttwo as d13p2} from './13/code';
import { partone as d14p1, parttwo as d14p2} from './14/code';
import { partone as d15p1, parttwo as d15p2} from './15/code';

console.log(`-- Day 1 --`);
console.log(`Part 1: ${d1p1}`);
console.log(`Part 2: ${d1p2}`);
console.log(`-- Day 2 --`);
console.log(`Part 1: ${d2p1}`);
console.log(`Part 2: ${d2p2}`);
console.log(`-- Day 3 --`);
console.log(`Part 1: ${d3p1}`);
console.log(`Part 2: ${d3p2}`);
console.log(`-- Day 4 --`);
console.log(`Part 1: ${d4p1}`);
console.log(`Part 2: ${d4p2}`);
console.log(`-- Day 5 --`);
console.log(`Part 1: ${d5p1}`);
console.log(`Part 2: ${d5p2}`);
console.log(`-- Day 6 --`);
console.log(`Part 1: ${d6p1}`);
console.log(`Part 2: ${d6p2}`);
console.log(`-- Day 7 --`);
console.log(`Part 1: ${d7p1}`);
console.log(`Part 2: ${d7p2}`);
console.log(`-- Day 8 --`);
console.log(`Part 1: ${d8p1}`);
console.log(`Part 2: ${d8p2}`);
console.log(`-- Day 9 --`);
console.log(`Part 1: ${d9p1}`);
console.log(`Part 2: ${d9p2}`);
console.log(`-- Day 10 --`);
console.log(`Part 1: ${d10p1}`);
console.log(`Part 2: ${d10p2}`);
console.log(`-- Day 11 --`);
console.log(`Part 1: ${d11p1}`);
console.log(`Part 2: ${d11p2}`);
console.log(`-- Day 12 --`);
console.log(`Part 1: ${d12p1}`);
console.log(`Part 2: ${d12p2}`);
console.log(`-- Day 13 --`);
console.log(`Part 1: ${d13p1}`);
console.log(`Part 2: ${d13p2}`);
console.log(`-- Day 14 --`);
console.log(`Part 1: ${d14p1}`);
console.log(`Part 2: ${d14p2}`);
console.log(`-- Day 15 --`);
console.log(`Part 1: ${d15p1}`);
console.log(`Part 2: ${d15p2}`);

console.log(`-- xxxxxx --`);